import { useState } from "react";
import { motion } from "framer-motion";
import { CalendarDays, Loader2, RefreshCw, Wand2 } from "lucide-react";
import { api } from "../lib/api";

// On-demand weekly "sleep coach" report, generated by the AI over the last
// 7 days of entries.
export default function WeeklyDigest() {
  const [digest, setDigest] = useState("");
  const [count, setCount] = useState(0);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState("");
  const [loaded, setLoaded] = useState(false);

  const generate = async () => {
    setLoading(true);
    setErr("");
    try {
      const r = await api.weeklyDigest();
      setDigest(r.digest);
      setCount(r.count);
      setLoaded(true);
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Couldn't build your digest.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="glass relative overflow-hidden rounded-3xl p-6">
      <div className="pointer-events-none absolute -right-12 -top-12 h-40 w-40 rounded-full bg-aurora-cyan/15 blur-3xl" />
      <div className="relative">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-aurora-cyan">
            <CalendarDays className="h-5 w-5" />
            <h2 className="font-display text-lg font-semibold text-white">
              Weekly sleep-coach report
            </h2>
          </div>
          {loaded && (
            <button
              onClick={generate}
              disabled={loading}
              className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-white/70 transition hover:text-white disabled:opacity-50"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
              Refresh
            </button>
          )}
        </div>

        {!loaded && !loading && (
          <div className="mt-4">
            <p className="text-sm text-white/55">
              A warm AI summary of your week — recurring symbols, mood shifts and
              one gentle suggestion.
            </p>
            <button onClick={generate} className="btn-aurora mt-4 text-sm">
              <Wand2 className="h-4 w-4" /> Generate this week's report
            </button>
          </div>
        )}

        {loading && (
          <div className="mt-5 flex items-center gap-2 text-sm text-white/60">
            <Loader2 className="h-4 w-4 animate-spin" /> Reading your week…
          </div>
        )}

        {err && <p className="mt-4 text-sm text-aurora-pink">{err}</p>}

        {loaded && !loading && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-4">
            <p className="whitespace-pre-line text-sm leading-relaxed text-white/85">
              {digest}
            </p>
            <p className="mt-3 text-xs text-white/35">
              Based on {count} dream{count === 1 ? "" : "s"} from the last 7 days.
            </p>
          </motion.div>
        )}
      </div>
    </div>
  );
}
